name: build-app

on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ready for build
        run: echo "Ready for build"

      - name: build for production
        run: npm install --save --legacy-peer-deps && npm run prod --if-present

      - uses: actions/upload-artifact@v4
        with: 
          name: app-build
          path: build

      - name: success message
        run: echo "Build successfully"

      -
